In [16]:
import tensorflow as tf
import numpy as np

In [17]:
# scalar or single data
scalar = tf.constant(10)
print(scalar)
# scalar.shape # zero order tensor
tf.rank(scalar)

tf.Tensor(10, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [18]:
# multiple data in row
vector = tf.constant([1,2,3,4,4])
print(tf.rank(vector))
vector.shape # 1 order tensor

tf.Tensor(1, shape=(), dtype=int32)


TensorShape([5])

In [12]:
vector2 = tf.constant([[1,2,3], [4,5,6]])
tf.rank(vector2)
print(vector2.shape)

(2, 3)


In [15]:
matrix = tf.constant([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]],
    [[13,14,15], [16,17,18]]
])
# shape (3,2,3)
# matrix.shape
print(tf.rank(matrix))
matrix

tf.Tensor(3, shape=(), dtype=int32)


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [22]:
# Create tensor
tensor0 = tf.zeros([2, 1, 3])
tensor0

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[0., 0., 0.]],

       [[0., 0., 0.]]], dtype=float32)>

In [26]:
# numpy to tensor
np_array = np.array([1,2,'c',7])

tf_ = tf.constant(np_array)
tf_

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'1', b'2', b'c', b'7'], dtype=object)>

In [32]:
# tensor to numpy
ts_array = tf.constant([1,2,5,7])
np_ = np.array(ts_array)
np_

ValueError: Can't convert Python sequence with mixed types to Tensor.