In [ ]:
# addition
# substraction
# multiplication
# division
# matrix multiplication

<llm-snippet-file>/home/bs00815/Desktop/MachineLearning/ml-dl-computer-vision-journey/5_image_with_deep_learning/tensorflow/2_tensor_operations.ipynb</llm-snippet-file>


In [9]:
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf
import numpy as np

# tensor creation
a = tf.constant([1, 2, 3])
b = tf.constant([[1, 2], [3, 4]])

print(">>> a: ", a)
print(">>> b: ", b)


>>> a:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
>>> b:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [10]:
# Arithmetic operations
c = tf.add(a, 5)
d = tf.subtract(a, 5)
e = tf.multiply(a, 5)
f = tf.divide(a, 5)
print("Addition: ", c)
print("Subtraction: ", d)
print("Multiplication: ", e)
print("Division: ", f)

Addition:  tf.Tensor([6 7 8], shape=(3,), dtype=int32)
Subtraction:  tf.Tensor([-4 -3 -2], shape=(3,), dtype=int32)
Multiplication:  tf.Tensor([ 5 10 15], shape=(3,), dtype=int32)
Division:  tf.Tensor([0.2 0.4 0.6], shape=(3,), dtype=float64)


In [14]:
# element-wise operations between tensors (broadcasting applies)

g = tf.constant([1, 2, 3])
h = tf.constant([[1,2,3], [4,5,6]])

#matrix addition
i = tf.add(g, h)
print("Matrix addition: g+h==", i)

print("\n")
# matrix multiplication
mat1 = tf.constant([[1, 2], [3, 4]])
mat2 = tf.constant([[5, 6], [7, 8]])
matmul = tf.matmul(mat1, mat2)
print("Matrix mul===", matmul)

Matrix addition: g+h== tf.Tensor(
[[2 4 6]
 [5 7 9]], shape=(2, 3), dtype=int32)


Matrix mul=== tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [16]:
# reshape
reshaped = tf.reshape(mat2, [4,1])
print(f'reshaped=={reshaped}\n')

sum_all = tf.reduce_sum(mat1)
mean_all = tf.reduce_mean(mat2)
sum_axis0 = tf.reduce_sum(mat2, axis=0)
sum_axis1 = tf.reduce_sum(mat2, axis=1)
print(f'sum_all=={sum_all}\nmean_all=={mean_all}\nsum_axis0=={sum_axis0}\nsum_axis1=={sum_axis1}')

reshaped==[[5]
 [6]
 [7]
 [8]]

sum_all==10
mean_all==6
sum_axis0==[12 14]
sum_axis1==[11 15]


In [18]:
#slicing
slice_example = tf.constant([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(f'slice_example=={slice_example[1, 1:3]}\n')

# Logical Operation
bool_tensor = tf.constant([True, False, True, False])
logical_and = tf.logical_and(bool_tensor, tf.constant([True, True, False, True]))
print(f'logical_and=={logical_and}\n')

slice_example==[7 8]

logical_and==[ True False False False]



In [21]:
# Casting type
float_tensor = tf.constant([1, 2, 3])
int_tensor = tf.cast(float_tensor, tf.float32)
print(f'int_tensor=={int_tensor.numpy()}')

int_tensor==[1. 2. 3.]


In [22]:
# random tensors
rando_ = tf.random.uniform([2,3], minval=0, maxval=10, dtype=tf.int32)
print(f'random_=={rando_.numpy()}')

random_==[[6 8 9]
 [6 6 7]]
