In [3]:
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf

tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print(tensor[0])      # First row → [1, 2, 3]
print(tensor[0, 1])   # First row, second column → 2
print(tensor[:, 1])   # All rows, second column → [2, 5]
print(tensor[1, :])   # Second row, all columns → [4, 5, 6]


tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [7]:
print(tensor[-1])       # Last row → [4, 5, 6]
print(tensor[:, -1])    # Last column → [3, 6]

tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([3 6], shape=(2,), dtype=int32)


In [8]:
# [start:stop] inclusive.
print(tensor[0:2, 1:3])  # Rows 0–1, columns 1–2 → [[2, 3], [5, 6]]

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)


In [9]:
# boolean masking
mask = tensor > 50
print(mask.numpy())   # Boolean matrix
print(tf.boolean_mask(tensor, mask))  # Values > 50 → [70 80 90]


[[False False False]
 [False False False]]
tf.Tensor([], shape=(0,), dtype=int32)


In [14]:
t = tf.range(1,13)
reshaped = tf.reshape(t, [4, 3])
reshaped

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [15]:
# flatten
flat = tf.reshape(t, [-1])
print(flat)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12], shape=(12,), dtype=int32)


In [17]:
# 8. Adding / Removing Dimensions
a = tf.constant([1, 2, 3])

# Add dimension
a_expanded = tf.expand_dims(a, axis=0)  # Shape: (1, 3)
a_expanded2 = tf.expand_dims(a, axis=-1) # Shape: (3, 1)

# Remove dimension
a_squeezed = tf.squeeze(a_expanded)     # Shape: (3,)
print(f"a_expanded: {a_expanded.numpy()}")
print(f"a_expanded2: {a_expanded2.numpy()}")
print(f"a_squeezed: {a_squeezed.numpy()}")



a_expanded: [[1 2 3]]
a_expanded2: [[1]
 [2]
 [3]]
a_squeezed: [1 2 3]
