In [4]:
import os

import numpy as np

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf

In [7]:
import tensorflow as tf

a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])   # shape (2,3)

b = tf.constant([10, 20, 30])  # shape (3,)

result = a + b
print(result.numpy())


[[11 22 33]
 [14 25 36]]


In [9]:
# type casting

x = tf.constant([1.5, 2.6, 3.2], dtype=tf.float32)
y = tf.cast(x, tf.int32)
print(y.numpy())
# মডেলে precision দরকার হলে float32 → float64 করা যায়।

[1 2 3]


In [10]:
# যেখানে প্রতিটি row-এর length আলাদা হয়। সাধারণ টেন্সরে সব row-এর length সমান হতে হয়, কিন্তু ragged tensor-এ সমান হতে হয় না।

rt = tf.ragged.constant([[1, 2, 3], [4, 5]])
print(rt.shape)
print(rt.shape)
# NLP-তে ভিন্ন দৈর্ঘ্যের sentence রাখতে কাজে লাগে।

(2, None)
(2, None)


In [14]:
st = tf.constant(["cat", "dog", "tiger"])
print(st)
print(tf.strings.length(st).numpy())  # প্রতিটি string-এর length
print(tf.strings.upper(st).numpy())   # সব ক্যাপিটাল
# 💡 Text preprocessing-এ দরকার হয়।

tf.Tensor([b'cat' b'dog' b'tiger'], shape=(3,), dtype=string)
[3 3 5]
[b'CAT' b'DOG' b'TIGER']


In [18]:
# যখন অনেক ডেটা zero বা missing, তখন পুরো dense tensor না বানিয়ে শুধু non-zero entry এবং তাদের অবস্থান রাখা হয় — মেমরি বাঁচে।

st = tf.sparse.SparseTensor(
    indices=[[0,0], [1,2]],
    values=["a", "b"],
    dense_shape=[3, 4]
)
print(st)

dense = tf.sparse.to_dense(st)
print(dense)
# 💡 অনেক বড় ম্যাট্রিক্সে, যেখানে বেশিরভাগ মান 0, sparse tensor ব্যবহার করলে মেমরি অনেক কম লাগে।

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([b'a' b'b'], shape=(2,), dtype=string), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[b'a' b'' b'' b'']
 [b'' b'' b'b' b'']
 [b'' b'' b'' b'']], shape=(3, 4), dtype=string)


In [7]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([[2],[1]])
arr1 + arr2

array([[3, 4, 5],
       [2, 3, 4]])